# Generated by Django 3.0.2 on 2020-01-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20200115_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='general_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=10)),
                ('height', models.IntegerField(max_length=10)),
                ('weight', models.IntegerField(max_length=10)),
                ('blood_group', models.CharField(max_length=10)),
                ('vision', models.FloatField(max_length=10)),
                ('gender', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=200)),
                ('adhar_number', models.IntegerField(max_length=30)),
                ('pan', models.CharField(max_length=100)),
                ('family_hist', models.CharField(max_length=200)),
                ('abnormalities', models.BooleanField(default=False)),
                ('income', models.IntegerField(max_length=10)),
                ('father_name', models.CharField(max_length=100)),
                ('fathers_occ', models.CharField(max_length=100)),
                ('mother_occ', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('pob', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('occupation', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('religious_minority', models.BooleanField(default=False)),
                ('prev_insurance', models.BooleanField(default=False)),
                ('nationality', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('sign', models.ImageField(upload_to='')),
                ('smoker', models.BooleanField(default=False)),
                ('alcohol', models.BooleanField(default=False)),
            ],
        ),
    ]
