# Generated by Django 3.0.2 on 2020-01-15 18:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_general_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_details',
            name='abnormalities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Diabetes', 'Diabetes'), ('Cancer', 'Cancer'), ('Eye Problem', 'Eye Problem'), ('Blood Pressure', 'Blood Pressure'), ('None', 'None')], max_length=47),
        ),
    ]
