# Generated by Django 3.0.2 on 2020-01-15 18:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_auto_20200115_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_details',
            name='abnormalities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Blind', 'Blind'), ('Deaf', 'Deaf'), ('Dyslexia', 'Dyslexia'), ('Physical deformation', 'Physical deformation'), ('Speech impairment', 'Speech impairment')], max_length=58),
        ),
        migrations.AlterField(
            model_name='general_details',
            name='family_hist',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Diabetes', 'Diabetes'), ('Cancer', 'Cancer'), ('Eye Problem', 'Eye Problem'), ('Blood Pressure', 'Blood Pressure'), ('None', 'None')], max_length=47),
        ),
    ]
