# Generated by Django 3.0.2 on 2020-01-15 18:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_auto_20200115_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_details',
            name='income',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Less than 5Lakh', 'Less than 5Lakh'), ('5 to 10Lakh', '5 to 10Lakh'), ('More than 10Lakh', 'More than 10Lakh')], max_length=44),
        ),
    ]
