# Generated by Django 3.0.2 on 2020-01-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_auto_20200115_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_details',
            name='alcohol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='general_details',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='general_details',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='general_details',
            name='prev_insurance',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='general_details',
            name='religious_minority',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='general_details',
            name='sign',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='general_details',
            name='smoker',
            field=models.CharField(max_length=10),
        ),
    ]
