# Generated by Django 3.0.2 on 2020-01-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0011_chronic_month2_chronic_month3_vital2_vital3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vital',
            name='vitals',
        ),
    ]
